# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_change', models.FloatField(default=0)),
                ('coin_basevolume', models.FloatField(default=0)),
                ('coin_perchange', models.FloatField(default=0)),
                ('coin_value', models.FloatField(default=0)),
                ('reqtime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinsapp.Coin')),
            ],
        ),
    ]
