# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coinproperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_perchange', models.FloatField(default=0)),
                ('coin_change', models.FloatField(default=0)),
                ('allvolume', models.FloatField(default=0)),
                ('volumechange', models.FloatField(default=0)),
                ('coin_ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='value',
            name='coin_change',
        ),
        migrations.RemoveField(
            model_name='value',
            name='coin_perchange',
        ),
    ]
