# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coinsapp', '0002_auto_20180120_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinproperties',
            name='coin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='coinsapp.Coin'),
            preserve_default=False,
        ),
    ]
