# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinsapp', '0003_coinproperties_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinproperties',
            name='coin_ticker',
        ),
    ]
