# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinsapp', '0004_remove_coinproperties_coin_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinproperties',
            name='allvolume',
        ),
        migrations.AddField(
            model_name='coinproperties',
            name='voluemchnage_time',
            field=models.FloatField(default=0),
        ),
    ]
