# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinsapp', '0005_auto_20180208_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinproperties',
            name='voluemchnage_time',
        ),
        migrations.AddField(
            model_name='coinproperties',
            name='volumechnage_time',
            field=models.FloatField(default=0),
        ),
    ]
