# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinsapp', '0006_auto_20180208_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinproperties',
            name='volumechange',
        ),
        migrations.RemoveField(
            model_name='coinproperties',
            name='volumechnage_time',
        ),
    ]
