# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinsapp', '0008_coinproperties_allvolume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinproperties',
            old_name='allvolume',
            new_name='volume_change',
        ),
    ]
