# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinsapp', '0009_auto_20180213_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinproperties',
            name='coin_change_30',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coinproperties',
            name='volume_change_30',
            field=models.FloatField(default=0),
        ),
    ]
