# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinsapp', '0010_auto_20180216_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinproperties',
            old_name='coin_change_30',
            new_name='coin_change_half',
        ),
        migrations.RenameField(
            model_name='coinproperties',
            old_name='volume_change_30',
            new_name='volume_change_half',
        ),
    ]
